name: merge

on:
  push:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/test.yaml

  lint:
    uses: ./.github/workflows/lint.yaml

  docs:
    uses: ./.github/workflows/docs.yaml

  build:
    needs: [test, lint, docs]
    uses: ./.github/workflows/build.yaml
